export const WELCOME = 'WELCOME';
export const QUIZ = 'QUIZ';
export const SUMMARY = 'SUMMARY';
export const RESTART_GAME = 'RESTART_GAME';
export const FETCHING_QUESTIONS = 'FETCHING_DATA';
export const FETCHING_QUESTIONS_SUCCESS = 'FETCHING_SUCCESS';
export const FETCHING_QUESTIONS_FAILURE = 'FETCHING_FAILURE';
export const QUESTION_ANSWERED = 'QUESTION_ANSWERED';
export const API_URL = 'https://opentdb.com/api.php?amount=10&difficulty=hard&type=boolean';
